### ISSUE TITLE
Reduce EEPROM writes during autoplay

### ISSUE THREAD

**Issue by terrag42** [evilgeniuslabs/bloom-v2#1]
I believe there was a modification to the Tree-v2 program that reduced the number of EEPROM writes by checking to see if autoplay mode was active before writing the current pattern index to EEPROM. Can this be done to Bloom-v2 as well? Adding an IF statement to line 833 in the main sketch would do the trick.

**Comment by jasoncoon** [comment]
Yeah, found it: https://github.com/evilgeniuslabs/tree-v2/pull/15/files

Good idea, I'll get that change made.

**Comment by jasoncoon** [comment]
Fixed in commit https://github.com/evilgeniuslabs/bloom-v2/commit/aebc43ce33c7149de88313e08c488a1be18f24d6
